# Generated by Django 3.0.8 on 2020-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('Mr', 'مرد'), ('Mrs', 'زن')], max_length=10)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('location', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
