# Generated by Django 3.0.8 on 2020-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Mr', 'male'), ('Mrs', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
